name: 01-building-blocks

on: pull_request:

jobs:
    echo-hello:
        runs-on: ubuntu-latest
        steps:
            - name: Say Hello
              run: echo "Hello World"
    
    echo-bye:
        runs-on: ubuntu-latest
        steps:
            - name: Success Step
              run: |
               echo "Congo!" 
               exit 0
            - name: Say Goodbye
              run: echo "Goodbye"

        

