name: 03 Workflow runners
on: push 

jobs:
  ubuntu-echo:
    runs-on: ubuntu-latest 
    steps: 
      - name: Show OS
        runs: |
          echo "This job is running on ubuntu runner"
          echo "Os runner is ${{github_runnerOS}}"
  
  windows-echo:
    runs-on: windows-latest
    steps:
      - name: Show Os
        shell: bash
        run: echo "This job is running on windows"
             echo "OS runner is ${{github_runnerOS}}"