name: 04 Create Actions

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 04-create-actions/react-app
    steps: 
      - name: Check-out code
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Install Dependencies
        run: npm install
      - name: Run Unit tests
        run: npm run test
        #dep
        #check out 
        