name: 05 2 Events and types
on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs: 
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: step one
        run: echo "This PR runs only when its closed" 