name: 15 artifacts
on: 
  workflow_dispatch
jobs:
    test-build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: 14-artifacts/react-app
        steps:
            - name: checkout code
              uses: actions/checkout@v4
            - name: setup node
              uses: actions/setup-node@v3
              with: 
                node-version: '20.x'
            - name: Download cached dependencies
              id: cache
              if: ${{ inputs.use-cache}}
              uses: actions/cache@v3
              with:
                path: 14-artifacts/react-app/node_modules
                key: deps-node-modules-${{ hashFiles('14-artifacts/react-app/package-lock.json') }}
              if: steps.cache.outputs.cache-hit != 'true'
              run: |
               npm install
            - name: Testing
              run: |
               npm run test
            - name: building
              run: | 
                npm run build
            - name: upload build files
              uses: actions/upload-artifacts@v4
              with:
                name: app
                path: 14-artifacts/react-app/build
    
    deploy:
         runs-on: ubuntu-latest
         steps:
            - name: download artifacts
              uses: actions/download-artifacts@v4
              with: 
                name: app
                path: build
            - name: show folder structure
              run: ls -R




