name: 15 matrics
on: workflow_dispatch
jobs:
    
    matrics-var: 
        name: ${{matrix.os}}-${{matrix.node}}
        runs-on: ${{matrix.os}}
        strategy: 
            fast-fail: false
            matrix: 
                node: [19,20]
                os:
                  - ubuntu-latest
                include:
                    - os: ubuntu-latest
                      tag: experimental
                    - os: ubuntu-latest
                      node-version: '21.x'
       
        steps:
            - name: setup-node
              uses: actions/setup-node@v3
              with: 
                 node-version: ${{matrix.node}}

            - name: fail if experimental
              if: ${{matrix.tag == 'experimental'}}
              run: exit 1
            - name: Perform tasks
              run: |
                sleep 10
                echo "Running tests on OS ${{matrix.os}} and NodeJS ${{matrix.node}}"
            - name: upload test results
              run: echo "Upload test results"
