name: 16 working with environments
on:
  workflow_dispatch:
      inputs:
        tar-env:
            type:
                environment
            default: staging
run-name: 16 environment ${{inputs.tar-env}} 
jobs:
    echo:
        runs-on: ubuntu-latest
        environment: ${{inputs.tar-env}}
        env: 
            my-env-value: ${{vars.tar-env || "defaultvalue"}}
            steps:
                - name: echo vars
                  run: echo "vars ${{vars.tar-env}}"

